const data = {
    products: [
      {
        _id: '1',
        name: 'NIKE Formal Shirt',
        category: 'Shirts',
        image: '/images/p1.jpg',
        price: 2000,
        countInStock: 10,
        brand: 'NIKE',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'MANGO Floral Shirt',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 1200,
        countInStock: 11,
        brand: 'MANGO',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'ONLY Long Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 1800,
        countInStock: 0,
        brand: 'ONLY',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'PUMA Ripped Jeans',
        category: 'Jeans',
        image: '/images/p4.jpg',
        price: 1900,
        countInStock: 8,
        brand: 'PUMA',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'MANGO Bell Bottoms',
        category: 'Jeans',
        image: '/images/p5.jpg',
        price: 2200,
        countInStock: 4,
        brand: 'MANGO',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'ONLY Skinny Jeans',
        category: 'Jeans',
        image: '/images/p6.jpg',
        price: 2100,
        countInStock: 12,
        brand: 'ONLY',
        rating: 4.5,
        numReviews: 12,
        description: 'high quality product',
      },
    ],
  };
  export default data;